config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root 'pages#home'
  get 'signup' => 'users#new'
  post 'signup' => 'users#create'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :tweets, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :tweets
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id"
  has_many :passive_relatioships, class_name: "Relationship", foreign_key: "followed_id"
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relatioships, source: :follower
  default_scope -> { order(created_at: :desc) }
  validates :name, presence: true
  validates :email, presence: true
  has_secure_password
  validates :password, presence: true

  # Defines a proto-feed
  def feed
    Tweet.where("user_id = ?", id)
  end

  # Follows a user
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  # Unfollows a user
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # Returns true if the current user is following the other user
  def following?(other_user)
    following.include?(other_user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

  private

  # Confirms a logged-in user
  def logged_in_user
    unless logged_in?
      store_location
      redirect_to login_url
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    if logged_in?
      @tweet = current_user.tweets.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :logged_in_user

  def create
    @user = User.find(params[:followed_id])
    current_user.follow(@user)
    respond_to do |format|
      format.html { redirect_to @user }
      format.js
    end
  end

  def destroy
    @user = Relationship.find(params[:id]).followed
    current_user.unfollow(@user)
    respond_to do |format|
      format.html { redirect_to @user }
      format.js
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to current_user
    else
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]
  before_action :correct_user, only: :destroy

  def create
    @tweet = current_user.tweets.build(tweet_params)
    if @tweet.save
      redirect_to root_url
    else
      @feed_items = []
      render 'pages/index'
    end
  end

  def destroy
    @tweet.destroy
    redirect_to request.referrer || root_url
  end

  private

    def tweet_params
      params.require(:tweet).permit(:content)
    end

    def correct_user
      @tweet = current_user.tweets.find_by(id: params[:id])
      redirect_to root_url if @tweet.nil?
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index]

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
    @tweets = @user.tweets.paginate(page: params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to @user
    else
      render 'new'
    end
  end

  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    # Before filters

    # Confirms a logged-in user
    def logged_in_user
      unless logged_in?
        redirect_to login_url
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any)
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def current_user?(user)
    user == current_user
  end

  # Returns true if the user is logged in, false otherwise
  def logged_in?
    !current_user.nil?
  end

  # Logs out the current user
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar for the given user
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: 'gravatar')
  end
end

app/views/layouts/_footer.html.slim
footer
  small
    The Mini Twitter by Mary Lutsyuk
  .nav
    ul
      li
        = link_to "Home", root_path

app/views/layouts/_header.html.slim
header.navbar class="navbar-fixed-top navbar-inverse"
  .container
    = link_to "Mini Twitter", root_path, id: "logo"
    .nav
      ul.nav.navbar-nav.navbar-right
        li
          = link_to "Home", root_path
        - if logged_in?
          li
            = link_to "Users", users_path
          li
            = link_to "Profile", current_user
          li
            = link_to "Log out", logout_path, method: "delete"
        - else
          li
            = link_to "Log in", login_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title MiniTwitter
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

    link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous"

  body
    .container
      = render 'layouts/header'
    
      == yield

      = render 'layouts/footer'

app/views/pages/home.html.slim
- if logged_in?
  .row
    aside.col-md-4
      section.user-info
        = render 'shared/user_info'
      section.stats
        = render 'shared/stats'
      section.tweet_form
        = render 'shared/tweet_form'
    .col-md-8
      h3 
        | Tweet Feed
      = render 'shared/feed'
- else
  .center.jumbotron
  
    h1 Welcome to the Mini Twitter!

    h2 Make your life more interesting!

    == link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary"

app/views/relationships/create.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/unfollow')) %>");
$("#followers").html('<%= @user.followers.count %>');

app/views/relationships/destroy.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/follow')) %>");
$("#followers").html('<%= @user.followers.count %>');

app/views/shared/_feed.html.slim
- if @feed_items.any?
  ol.tweets
    = render @feed_items
  = will_paginate @feed_items

app/views/shared/_stats.html.slim
- @user ||= current_user
.stats
  = link_to following_user_path(@user)
    strong#following.stat
      = @user.following.count
    |  following 
  = link_to followers_user_path(@user)
    strong#followers.stat
      = @user.followers.count
    |  followers 

app/views/shared/_tweet_form.html.slim
= form_for(@tweet) do |f|
  .field
    = f.text_area :content, placeholder: "Compose new tweet..."
  = f.submit "Post", class: "btn btn-primary"

app/views/shared/_user_info.html.slim
= link_to gravatar_for(current_user, size: 50), current_user
h1
  = current_user.name
span
  = link_to "view my profile", current_user
span
  = pluralize(current_user.tweets.count, "tweet")

app/views/tweets/_tweet.html.slim
| <li id="tweet- 
= tweet.id 
| "> 
= link_to gravatar_for(tweet.user, size: 50), tweet.user 
span.user 
  = link_to tweet.user.name, tweet.user 
span.content 
  = tweet.content 
span.timestamp 
  | Posted 
  = time_ago_in_words(tweet.created_at)
  |  ago. 
  - if current_user?(tweet.user)
    = link_to "delete", tweet, method: :delete, data: { confirm: "Are you sure?" }

app/views/users/_follow.html.slim
= form_for(current_user.active_relationships.build, remote: true) do |f|
  div #{hidden_field_tag :followed_id, @user.id}
  = f.submit "Follow", class: "btn btn-primary"

app/views/users/_follow_form.html.slim
- unless current_user?(@user)
  #follow_form
  - if current_user.following?(@user)
    = render 'unfollow'
  - else
    = render 'follow'

app/views/users/_unfollow.html.slim
= form_for(current_user.active_relationships.find_by(followed_id: @user.id), html: { method: :delete }, remote: true) do |f|
  = f.submit "Unfollow", class: "btn"

app/views/users/index.html.slim
h1 All users

= will_paginate

ul.users
  - @users.each do |user|
    li
      = gravatar_for user, size: 50
      = link_to user.name, user

= will_paginate

app/views/users/new.html.slim
h1 Sign up
.row
  .col-md-6.col-md-offset-3
    = form_for(@user) do |f|
            
      = f.label :name
      = f.text_field :name, class: 'form-control'
      
      = f.label :email
      = f.email_field :email, class: 'form-control'
      
      = f.label :password
      = f.password_field :password, class: 'form-control'
      
      = f.label :password_confirmation, "Confirmation"
      = f.password_field :password_confirmation, class: 'form-control'
      
      = f.submit "Create my account", class: "btn btn-primary"

app/views/users/show.html.slim
.row
  aside.col-md-4
    section.user_info
      h1
        = gravatar_for @user
        = @user.name
    section.stats
      = render 'shared/stats'
  .col-md-8
    = render 'follow_form' if logged_in?
    - if @user.tweets.any?
      h3 
        | Tweets (#{@user.tweets.count})
      ol.tweets
        = render @tweets
      = will_paginate @tweets

app/views/users/show_follow.html.slim
- provide(:title, @title)
.row
  aside.col-md-4
    section.user_info
      = gravatar_for @user
      h1
        = @user.name
      span
        = link_to "view my profile", @user
      span
        b
          | Tweets: #{@user.tweets.count}
    section.stats
      = render 'shared/stats'
      - if @users.any?
        .user_avatars
          - @users.each do |user|
            = link_to gravatar_for(user, size: 30), user